[project]
name = "lab-reader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.133.0",
    "filetype>=1.2.0",
    "httpx>=0.28.1",
    "langchain>=1.2.10",
    "langchain-core>=1.2.15",
    "langchain-google-genai>=4.2.1",
    "python-dotenv>=1.2.1",
    "python-multipart>=0.0.22",
    "uvicorn>=0.41.0",
]
